camera_topics:
  front:
    image_topic: "/alphasense_driver_ros/cam4/debayered"
    info_topic: "/alphasense_driver_ros/cam4/camera_info"
    use_for_training: true
    publish_confidence: true
    publish_input_image: true
    scheduler_weight: 1
  left:
    image_topic: "/alphasense_driver_ros/cam3/debayered"
    info_topic: "/alphasense_driver_ros/cam3/camera_info"
    use_for_training: false
    publish_confidence: true
    publish_input_image: true
    scheduler_weight: 1
  right:
    image_topic: "/alphasense_driver_ros/cam5/debayered"
    info_topic: "/alphasense_driver_ros/cam5/camera_info"
    use_for_training: false
    publish_confidence: true
    publish_input_image: true
    scheduler_weight: 1

# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448